matrix:
  include:
    # - language: android
    #   dist: trusty
    #   cache: npm
    #   android:
    #     components:
    #       # use the latest revision of Android SDK Tools
    #       - tools
    #       - platform-tools

    #       # The BuildTools version used by your project
    #       - build-tools-28.0.3

    #       # The SDK version used to compile your project
    #       - android-28

    #       # Additional components
    #       - extra-google-google_play_services
    #       - extra-google-m2repository
    #       - extra-android-m2repository
    #   install:
    #     - nvm install 12.14.0
    #     - npm i
    #   before_script:
    #     - cd android
    #   script:
    #     - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode11.3
      podfile: ios/Podfile
      cache:
        cocoapods: true
        npm: false
        yarn: false
      before_install:
        # Repo for Yarn
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install:
        - brew update
        - brew tap wix/brew
        - brew install applesimutils
        - gem install cocoapods
        - nvm install 12.14.0
        - yarn install
      before_script:
        - cd ios
        - pod install
        - cd ..
      script:
        - yarn detox-build:iosRelease | xcpretty
        - yarn detox-test:iosRelease --cleanup
