export const userActions = {
  GET_TOKENS_SUCCESS: "GET_TOKENS_SUCCESS",
  GET_PROFILE_ERROR: "GET_PROFILE_SUCCESS",
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILE_SUCCESS: "PROFILE_SUCCESS",
  REDO_LOGIN: "REDO_LOGIN",
};

export const globalActions = {
  REHYDRATE_FROM_API: "REHYDRATE_FROM_API",
  PUSH_ACTION_TO_RESTART: "PUSH_ACTION_TO_RESTART",
  CLEAR_ACTIONS_TO_RESTART: "CLEAR_ACTIONS_TO_RESTART",
};

export const playlistActions = {
  CLEAR_PLAYLIST_DETAILS: "CLEAR_PLAYLIST_DETAILS",
  GET_PLAYLIST_BY_ID: "GET_PLAYLIST_BY_ID",
  GET_PLAYLIST_BY_ID_ERROR: "GET_PLAYLIST_BY_ID_ERROR",
  GET_CURRENT_USER_PLAYLISTS: "GET_CURRENT_USER_PLAYLISTS",
  GET_CURRENT_USER_PLAYLISTS_SUCCESS: "GET_CURRENT_USER_PLAYLISTS_SUCCESS",
  GET_CURRENT_USER_PLAYLISTS_ERROR: "GET_CURRENT_USER_PLAYLISTS_ERROR",
  GET_PLAYLIST_DETAILS_SUCCESS: "GET_PLAYLIST_DETAILS_SUCCESS",
};

export const albumActions = {
  GET_ALBUM: "GET_ALBUM",
  GET_ALBUM_SUCCESS: "GET_ALBUM_SUCCESS",
  GET_ALBUM_ERROR: "GET_ALBUM_ERROR",
  GET_MULTIPLE_ALBUM: "GET_MULTIPLE_ALBUM",
  GET_MULTIPLE_ALBUM_SUCCESS: "GET_MULTIPLE_ALBUM_SUCCESS",
  GET_MULTIPLE_ALBUM_ERROR: "GET_MULTIPLE_ALBUM_ERROR",
};

export const libraryActions = {
  GET_CURRENT_USER_SAVED_TRACKS: "GET_CURRENT_USER_SAVED_TRACKS",
  GET_CURRENT_USER_SAVED_TRACKS_SUCCESS:
    "GET_CURRENT_USER_SAVED_TRACKS_SUCCESS",
  GET_CURRENT_USER_SAVED_TRACKS_ERROR: "GET_CURRENT_USER_SAVED_TRACKS_ERROR",
  GET_CURRENT_USER_SAVED_ALBUMS: "GET_CURRENT_USER_SAVED_ALBUMS",
  GET_CURRENT_USER_SAVED_ALBUMS_SUCCESS:
    "GET_CURRENT_USER_SAVED_ALBUMS_SUCCESS",
  GET_CURRENT_USER_SAVED_ALBUMS_ERROR: "GET_CURRENT_USER_SAVED_ALBUMS_ERROR",
};

export const browseActions = {
  GET_ALL_FEATURED_PLAYLISTS: "GET_ALL_FEATURED_PLAYLISTS",
  GET_ALL_FEATURED_PLAYLISTS_SUCCESS: "GET_ALL_FEATURED_PLAYLISTS_SUCCESS",
  GET_ALL_FEATURED_PLAYLISTS_ERROR: "GET_ALL_FEATURED_PLAYLISTS_ERROR",
  GET_ALL_CATEGORIES_FOR_COUNTRY: "GET_ALL_CATEGORIES_FOR_COUNTRY",
  GET_ALL_CATEGORIES_FOR_COUNTRY_SUCCESS:
    "GET_ALL_CATEGORIES_FOR_COUNTRY_SUCCESS",
  GET_ALL_CATEGORIES_FOR_COUNTRY_ERROR: "GET_ALL_CATEGORIES_FOR_COUNTRY_ERROR",
  GET_CATEGORY_BY_ID: "GET_CATEGORY_BY_ID",
  GET_CATEGORY_BY_ID_SUCCESS: "GET_CATEGORY_BY_ID_SUCCESS",
  GET_CATEGORY_BY_ID_ERROR: "GET_CATEGORY_BY_ID_ERROR",
  GET_MORE_CATEGORY_BY_ID_SUCCESS: "GET_MORE_CATEGORY_BY_ID_SUCCESS",
  IS_LOADING: "IS_LOADING",
  IS_NOT_LOADING: "IS_NOT_LOADING",
};

export const personalizationActions = {
  GET_USER_TOP_ARTISTS: "GET_USER_TOP_ARTISTS",
  GET_USER_TOP_ARTISTS_SUCCESS: "GET_USER_TOP_ARTISTS_SUCCESS",
  GET_USER_TOP_ARTISTS_ERROR: "GET_USER_TOP_ARTISTS_ERROR",
};

export const followActions = {
  GET_CURRENT_USER_FOLLOWED_ARTISTS: "GET_CURRENT_USER_FOLLOWED_ARTISTS",
  GET_CURRENT_USER_FOLLOWED_ARTISTS_SUCCESS:
    "GET_CURRENT_USER_FOLLOWED_ARTISTS_SUCCESS",
  GET_CURRENT_USER_FOLLOWED_ARTISTS_ERROR:
    "GET_CURRENT_USER_FOLLOWED_ARTISTS_ERROR",
};

export const playerActions = {
  RECENTLY_PLAYED_TRACKS: "RECENTLY_PLAYED_TRACKS",
  RECENTLY_PLAYED_TRACKS_ERROR: "RECENTLY_PLAYED_TRACKS_ERROR",
};

export const artistActions = {
  SET_ARTIST_ID: "SET_ARTIST_ID",
};

export const searchActions = {
  QUERY: "QUERY",
  QUERY_SUCCESS: "QUERY_SUCCESS",
  QUERY_ERROR: "QUERY_ERROR",
  QUERY_LOADING: "QUERY_LOADING",
  QUERY_EMPTY: "QUERY_EMPTY",
  QUERY_SAVE: "QUERY_SAVE",
  QUERY_DELETE: "QUERY_DELETE",
  QUERY_DELETE_ALL: "QUERY_DELETE_ALL",
  SET_SEE_ALL_TYPE: "SET_SEE_ALL_TYPE",
};
