export const authActions = {
  GET_TOKENS_SUCCESS: "GET_TOKENS_SUCCESS",
  SET_TOKENS: "SET_TOKENS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  ERROR: "ERROR",
  GET_PROFILE: "GET_PROFILE",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
};

export const loadingActions = {
  LOADING: "LOADING",
  DONE: "DONE",
};
